name: Build Windows Executable - PyInstaller
# Description:
# Most of my projects come with a build.bat script that uses PyInstaller to freeze the examples
# to an executable file. This Action will set up the environment and run this build.bat script,
# then upload the resulting executables to a google cloud bucket.
# Additionally, the executables will be compressed and encrypted using 7z.

on:
  push:
    branches:
      - main # Trigger on push to main branch
    tags:
      - '*'  # Trigger on any tag push

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller virtualenv

    - name: Run Batch File to Build Executable
      run: builder\pyinstaller\build.bat

    - name: Compress executables
      run: |
        "C:\Program Files\7-Zip\7z.exe" a secure.7z *.exe -pprotected
      working-directory: ${{ github.workspace }}/builder/pyinstaller
      shell: cmd

    - name: Upload Artifacts for Download
      uses: actions/upload-artifact@v2
      with:
        name: executables.zip
        path: builder\pyinstaller\*.exe
        retention-days: 10

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          builder\pyinstaller\*.exe
          builder\pyinstaller\*.7z
